CREATE TABLE tb_product (
  id SERIAL PRIMARY KEY,
  SKU VARCHAR(255) UNIQUE NOT NULL,
  name VARCHAR(255) UNIQUE NOT NULL,
  imgUrl VARCHAR(255) UNIQUE NOT NULL,
  quantity INT,
  date TIMESTAMP,
  GTIN VARCHAR(255) UNIQUE NOT NULL
);